import { Inter } from "next/font/google";
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Staff App",
  description: "Generated by NextJS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer position="top-center" autoClose={1000}/>
        <Navbar/>
        <main className="container">
          {children}
        </main>
      </body>
    </html>
  );
}
